### ISSUE TITLE
Feature Request : Support insecure SSL (ignore SSL check)

### ISSUE THREAD

**Issue by ghost** [kedpter/M3u8Downloader#1]
* m3u8_dl version: 0.1.5
* Python version: Python 3.7.3rc1
* Operating System: Debian Buster (4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux)

### Description

Some streaming servers, whilst protected with SSL, do not have full certificate chain.

This causes urllib3 to fail, in similar to
```Traceback (most recent call last):
  File "/home/mason/myenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/mason/myenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/mason/myenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/mason/myenv/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/mason/myenv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```

### Request

Proposal to add parameter, such as `--no-check-certificate` or `--insecure`

**Comment by kedpter** [comment]
Thank you for pointing it out ! I'm pretty new to github, and it means a lot to me since you are the first one to reply back.

I have added the parameter `--insecure` to ignore verify, and another opposite parameter `--cerfile path` to validate with CAs. 

This is untested since I dont have such a link. Hope it would work.

m3u8_dl version: 0.1.7
